import Head from 'next/head';
import Link from "next/link";
import {BiWorld} from "react-icons/bi";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiOutlineMenu, AiOutlineClose, AiFillLinkedin, AiFillGithub} from "react-icons/ai";
import Image from 'next/image';
import avatar from "../public/avatar.png";
import { useState } from 'react';
import PortfolioList from '@/components/PortfolioList';
import About from '@/components/About';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  const [nav, setNav] = useState(false);

  const handleNav = () => {
    setNav(!nav)
  }

  return (
    <div>
      <Head>
        <title>Elijas portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={darkMode ? "dark" : ""}>
      <main className=' bg-green-50 text-mygreen-22 px-10 lg:px-20 dark:bg-mygreen-11 dark:text-green-50'>
        <div className='hero'>
        <header>

          {/* Menu */}
          <nav className='py-10 flex justify-between items-center'>
          <ul className='hidden sm:flex gap-5 md:text-xl font-burtons'>
            <li><Link href="/"><BiWorld /></Link></li>
            <li><Link href="/#portfolio">Portfolio</Link></li>
            <li><Link href="/#about">Om mig</Link></li>
          </ul>
          <ul className='hidden sm:flex items-center gap-5'>
            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
          </ul>
          
          {/* Mobile button */}
          <div onClick={handleNav} className="block sm:hidden z-10">
            {nav ? <AiOutlineClose size={20} /> : <AiOutlineMenu size={20} />}
          </div>
          {/* Mobile menu */}
          <div className={`sm:hidden dark:bg-black bg-white absolute top-0 ${nav ? 'left-0' : 'left-[-100%]'} right-0 bottom-0 flex justify-center items-center w-full h-screen text-center`}>
          <ul className='font-burtons'>
            <li onClick={handleNav} className='p-4 cursor-pointer text-4xl'><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}/></li>
            <li onClick={handleNav} className='p-4 text-4xl'><Link href="/">Start</Link></li>
            <li onClick={handleNav} className='p-4 text-4xl'><Link href="/#portfolio">Portfolio</Link></li>
            <li onClick={handleNav} className='p-4 text-4xl'><Link href="/#about">Om mig</Link></li>
          </ul>
          </div>
          </nav>
        </header>
        <section>
          <div className=' text-center p-10'>
            <h1 className=' text-5xl pb-2 dark:text-green-200 text-mygreen-55 font-medium md:text-5xl'>Elijas Andersson</h1>
            <h2 className='text-2xl py-2 md:text-3xl'>GIS-ingenjör</h2>
            <h3 className='text-xl py-2 md:text-2xl'>med utvecklarkompetens</h3>
            {/* <h3 className='mt-3 text-sm md:text-md max-w-md'>
              Digitala kartor för webb och utskrift, webbutveckling och systemutveckling.</h3> */}
          </div>
          <div className='text-5xl flex justify-center gap-5 py-3'>
            <a href='https://www.linkedin.com/in/elijas-andersson/' target="_blank"><AiFillLinkedin /></a>
            <a href='https://github.com/teros4me' target="_blank"><AiFillGithub /></a>
          </div>
          <div className='justify-center pt-10 md:ml-auto w-40 md:w-60 lg:w-80'>
            <Image src={avatar} alt={"Avatarbild på Elijas"} />
          </div>
        </section>
        </div>
        <section>
          <div>
            <h3 className="text-3xl pt-20" id='portfolio'>Portfolio</h3>
            <p>Fler projekt finns på <a href='https://github.com/teros4me' target="_blank">https://github.com/teros4me</a></p>
            <PortfolioList />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl pt-20" id='about'>Om mig</h3>
            <About />
          </div>
        </section>
        <footer className='pt-20 pb-10 italic'>
          &copy; Elijas Andersson 2023. Skapad i React/NextJs med Tailwind css. Uppdaterad: 2025-08-12
        </footer>
      </main>
      </div>
    </div>
  )
}
